---
dist: xenial
sudo: required
language: python
python: '3.7'
branches:
  only:
    - master

env:
  - MOLECULE_DISTRO=centos6
  - MOLECULE_DISTRO=centos7
  - MOLECULE_DISTRO=debian9
  - MOLECULE_DISTRO=ubuntu1804

services:
  - docker

before_script:
  - cd ../
  - mv ansible-role-tookit daixijun.tookit
  - cd daixijun.tookit

install:
  - pip install ansible molecule docker

script:
  - molecule test

notifications:
  webhooks:
    - https://galaxy.ansible.com/api/v1/notifications/
