---
dist: xenial
sudo: required
language: python

services:
  - docker

before_script:
  - cd ../
  - mv ansible-role-toolkit daixijun.toolkit
  - cd daixijun.toolkit
  - ansible-galaxy install -r requirements.yml --roles-path=../

install:
  - pip install ansible molecule docker

script:
  - molecule test

notifications:
  webhooks:
    - https://galaxy.ansible.com/api/v1/notifications/
